// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-install-zotlight'
  | 'pref-open-zotlight'
  | 'pref-title'
  | 'pref-uninstall-zotlight';
